import { defineConfig } from "wxt";
import tailwindcss from "@tailwindcss/vite";

// See https://wxt.dev/api/config.html
export default defineConfig({
  vite: () => ({ plugins: [tailwindcss()] }),
  modules: ["@wxt-dev/auto-icons", "@wxt-dev/module-react"],
  autoIcons: {
    baseIconPath: "public/icon.svg",
  },
  manifest: {
    name: "arXiv Downloader",
    permissions: ["activeTab", "downloads", "scripting"],
    action: {},
    // The 'icons' property will be automatically generated by @wxt-dev/auto-icons
  },
  webExt: {
    startUrls: ["https://arxiv.org"],
  },
});
